'use client';

import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // ... (rest of translations remain the same, adding specific ones below)
    home: 'Home',
    messages: 'Messages',
    post: 'Post',
    profile: 'Profile',
    login: 'Login',
    postAd: '+ Post Ad',
    postAdSubmit: 'Post Your Ad',
    allLocations: 'All of Bangladesh',
    searchPlaceholder: 'Search product or service',
    searchBtn: 'Search',
    allAds: 'All Ads →',
    browseCategories: 'Browse Categories',
    freshRecommendations: 'Fresh recommendations',
    selectCategory: 'Select Category',
    selectLocation: 'Select Location',
    title: 'Title',
    photos: 'Photos (up to 5)',
    price: 'Price',
    description: 'Description',
    contactPhone: 'Contact Phone',
    postingAd: 'Posting...',
    category: 'Category',
    location: 'Location',
    condition: 'Condition',
    new: 'New',
    used: 'Used',
    chat: 'Chat',
    account: 'Account',
    favorites: 'Favorites',
    settings: 'Settings',
    support: 'Support',
    logout: 'Logout',
    myAds: 'My Ads',
    myMessages: 'My Messages',
    noMessages: 'You have no messages yet.',
    browseAds: 'Browse Ads',
    typeMessage: 'Type a message...',
    online: 'Online',
    offline: 'Offline',
    active: 'Active',
    addPhoto: 'Add Photo',
    processing: 'Processing...',
    postNewAd: 'Post New Ad',
    myAccount: 'My Account',
    deleteConfirm: 'Are you sure you want to delete this ad?',
    deleteSuccess: 'Ad deleted successfully.',
    deleteFail: 'Delete failed: ',
    adNotFound: 'Ad not found or already deleted.',
    noAdsPosted: "You haven't posted any ads yet.",
    edit: 'Edit',
    delete: 'Delete',
    loggedInAs: 'Logged in as:',
    memberSince: 'Member since',
    verifiedSeller: 'Verified Seller',
    noImage: 'No Image Available',
    noAds: 'No ads found.',
    loading: 'Loading...',
    apply: 'Apply',
    reset: 'Reset',
    min: 'Min',
    max: 'Max',
    results: 'results',
    filterAds: 'Filter Ads',
    postedOn: 'Posted on:',
    safetyTips: 'Safety Tips',
    safetyTip1: 'Meet in a safe, public place',
    safetyTip2: "Don't pay in advance",
    safetyTip3: 'Inspect the item before buying',
    showPhone: 'Click to show phone',
    chatWithSeller: 'Chat with seller',
    noSub: 'No sub-categories available',
    searchCat: 'Search category...',
    searchLoc: 'Search location...',
    selectDiv: 'Select Division',
    selectDist: 'Select District',

    // Divisions
    'Dhaka': 'Dhaka',
    'Chattogram': 'Chattogram',
    'Rajshahi': 'Rajshahi',
    'Khulna': 'Khulna',
    'Barishal': 'Barishal',
    'Sylhet': 'Sylhet',
    'Rangpur': 'Rangpur',
    'Mymensingh': 'Mymensingh',
    'All of Dhaka Division': 'All of Dhaka Division',
    'All of Chattogram Division': 'All of Chattogram Division',
    'All of Rajshahi Division': 'All of Rajshahi Division',
    'All of Khulna Division': 'All of Khulna Division',
    'All of Barishal Division': 'All of Barishal Division',
    'All of Sylhet Division': 'All of Sylhet Division',
    'All of Rangpur Division': 'All of Rangpur Division',
    'All of Mymensingh Division': 'All of Mymensingh Division',

    // Districts (Common ones)
    'Dhaka City': 'Dhaka City',
    'Gazipur': 'Gazipur',
    'Tangail': 'Tangail',
    'Faridpur': 'Faridpur',
    'Gopalganj': 'Gopalganj',
    'Comilla': 'Comilla',
    'Bogra': 'Bogra',
    'Jessore': 'Jessore',
    'Cox\'s Bazar': 'Cox\'s Bazar',
    'Sylhet City': 'Sylhet City',

    // Categories
    'Electronics': 'Electronics',
    'Vehicles': 'Vehicles',
    'Property': 'Property',
    'Jobs': 'Jobs',
    'Mobile Phones': 'Mobile Phones',
    'Computers': 'Computers',
    'TVs & Audio': 'TVs & Audio',
    'Cars': 'Cars',
    'Motorcycles': 'Motorcycles',
    'For Rent': 'For Rent',
    'For Sale': 'For Sale',
  },
  bn: {
    home: 'হোম',
    messages: 'মেসেজ',
    post: 'পোস্ট',
    profile: 'প্রোফাইল',
    login: 'লগইন',
    postAd: '+ বিজ্ঞাপন দিন',
    postAdSubmit: 'বিজ্ঞাপন দিন',
    allLocations: 'সমগ্র বাংলাদেশ',
    searchPlaceholder: 'পণ্য বা সেবা খুঁজুন',
    searchBtn: 'খুঁজুন',
    allAds: 'সব বিজ্ঞাপন →',
    browseCategories: 'ক্যাটাগরি ব্রাউজ করুন',
    freshRecommendations: 'সদ্য আসা বিজ্ঞাপনগুলো',
    selectCategory: 'ক্যাটাগরি নির্বাচন করুন',
    selectLocation: 'অবস্থান নির্বাচন করুন',
    title: 'শিরোনাম',
    photos: 'ছবি (৫টি পর্যন্ত)',
    price: 'দাম',
    description: 'বিবরণ',
    contactPhone: 'যোগাযোগের ফোন নম্বর',
    postingAd: 'পোস্ট হচ্ছে...',
    category: 'ক্যাটাগরি',
    location: 'অবস্থান',
    condition: 'অবস্থা',
    new: 'নতুন',
    used: 'ব্যবহৃত',
    chat: 'চ্যাট',
    account: 'অ্যাকাউন্ট',
    favorites: 'প্রিয়',
    settings: 'সেটিংস',
    support: 'সহায়তা',
    logout: 'লগআউট',
    myAds: 'আমার বিজ্ঞাপন',
    myMessages: 'আমার মেসেজ',
    noMessages: 'আপনার কোনো মেসেজ নেই।',
    browseAds: 'বিজ্ঞাপন দেখুন',
    typeMessage: 'মেসেজ লিখুন...',
    online: 'অনলাইন',
    offline: 'অফলাইন',
    active: 'সক্রিয়',
    addPhoto: 'ছবি যোগ করুন',
    processing: 'প্রক্রিয়া চলছে...',
    postNewAd: 'নতুন বিজ্ঞাপন দিন',
    myAccount: 'আমার অ্যাকাউন্ট',
    deleteConfirm: 'আপনি কি নিশ্চিত যে এই বিজ্ঞাপনটি মুছে ফেলতে চান?',
    deleteSuccess: 'বিজ্ঞাপনটি সফলভাবে মুছে ফেলা হয়েছে।',
    deleteFail: 'মুছে ফেলতে সমস্যা: ',
    adNotFound: 'বিজ্ঞাপনটি খুঁজে পাওয়া যায়নি।',
    noAdsPosted: 'আপনি এখনো কোনো বিজ্ঞাপন দেননি।',
    edit: 'এডিট',
    delete: 'মুছে ফেলুন',
    loggedInAs: 'লগৃত:',
    memberSince: 'সদস্য হয়েছেন',
    verifiedSeller: 'ভেরিফাইড বিক্রেতা',
    noImage: 'কোনো ছবি নেই',
    noAds: 'কোনো বিজ্ঞাপন পাওয়া যায়নি।',
    loading: 'লোডিং...',
    apply: 'প্রয়োগ করুন',
    reset: 'রিসেট',
    min: 'সর্বনিম্ন',
    max: 'সর্বোচ্চ',
    results: 'ফলাফল',
    filterAds: 'ফিল্টার করুন',
    postedOn: 'পোস্ট করা হয়েছে:',
    safetyTips: 'নিরাপত্তা টিপস',
    safetyTip1: 'নিরাপদ জায়গায় দেখা করুন',
    safetyTip2: 'অগ্রিম টাকা দেবেন না',
    safetyTip3: 'পণ্যটি ভালোভাবে যাচাই করে নিন',
    showPhone: 'নম্বর দেখতে ক্লিক করুন',
    chatWithSeller: 'বিক্রেতার সাথে চ্যাট করুন',
    noSub: 'কোনো সাব-ক্যাটাগরি নেই',
    searchCat: 'ক্যাটাগরি খুঁজুন...',
    searchLoc: 'লোকেশন খুঁজুন...',
    selectDiv: 'বিভাগ নির্বাচন করুন',
    selectDist: 'জেলা নির্বাচন করুন',

    // Divisions
    'Dhaka': 'ঢাকা',
    'Chattogram': 'চট্টগ্রাম',
    'Rajshahi': 'রাজশাহী',
    'Khulna': 'খুলনা',
    'Barishal': 'বরিশাল',
    'Sylhet': 'সিলেট',
    'Rangpur': 'রংপুর',
    'Mymensingh': 'ময়মনসিংহ',
    'All of Dhaka Division': 'সমগ্র ঢাকা বিভাগ',
    'All of Chattogram Division': 'সমগ্র চট্টগ্রাম বিভাগ',
    'All of Rajshahi Division': 'সমগ্র রাজশাহী বিভাগ',
    'All of Khulna Division': 'সমগ্র খুলনা বিভাগ',
    'All of Barishal Division': 'সমগ্র বরিশাল বিভাগ',
    'All of Sylhet Division': 'সমগ্র সিলেট বিভাগ',
    'All of Rangpur Division': 'সমগ্র রংপুর বিভাগ',
    'All of Mymensingh Division': 'সমগ্র ময়মনসিংহ বিভাগ',

    // Districts (Full 64 Districts + City corporations)
    'Dhaka City': 'ঢাকা সিটি',
    'Faridpur': 'ফরিদপুর',
    'Gazipur': 'গাজীপুর',
    'Gopalganj': 'গোপালগঞ্জ',
    'Kishoreganj': 'কিশোরগঞ্জ',
    'Madaripur': 'মাদারীপুর',
    'Manikganj': 'মানিকগঞ্জ',
    'Munshiganj': 'মুন্সীগঞ্জ',
    'Narayanganj': 'নারায়ণগঞ্জ',
    'Narsingdi': 'নরসিংদী',
    'Rajbari': 'রাজবাড়ী',
    'Shariatpur': 'শরীয়তপুর',
    'Tangail': 'টাঙ্গাইল',
    'Chattogram City': 'চট্টগ্রাম সিটি',
    'Bandarban': 'বান্দরবান',
    'Brahmanbaria': 'ব্রাহ্মণবাড়িয়া',
    'Chandpur': 'চাঁদপুর',
    'Chattogram': 'চট্টগ্রাম',
    'Comilla': 'কুমিল্লা',
    'Cox\'s Bazar': 'কক্সবাজার',
    'Feni': 'ফেনী',
    'Khagrachhari': 'খাগড়াছড়ি',
    'Lakshmipur': 'লক্ষ্মীপুর',
    'Noakhali': 'নোয়াখালী',
    'Rangamati': 'রাঙ্গামাটি',
    'Rajshahi City': 'রাজশাহী সিটি',
    'Bogra': 'বগুড়া',
    'Joypurhat': 'জয়পুরহাট',
    'Naogaon': 'নওগাঁ',
    'Natore': 'নাটোর',
    'Chapainawabganj': 'চাঁপাইনবাবগঞ্জ',
    'Pabna': 'পাবনা',
    'Rajshahi': 'রাজশাহী',
    'Sirajganj': 'সিরাজগঞ্জ',
    'Khulna City': 'খুলনা সিটি',
    'Bagerhat': 'বাগেরহাট',
    'Chuadanga': 'চুয়াডাঙ্গা',
    'Jessore': 'যশোর',
    'Jhenaidah': 'ঝিনাইদহ',
    'Khulna': 'খুলনা',
    'Kushtia': 'কুষ্টিয়া',
    'Magura': 'মাগুরা',
    'Meherpur': 'মেহেরপুর',
    'Narail': 'নড়াইল',
    'Satkhira': 'সাতক্ষীরা',
    'Barishal City': 'বরিশাল সিটি',
    'Barguna': 'বরগুনা',
    'Barishal': 'বরিশাল',
    'Bhola': 'ভোলা',
    'Jhalokati': 'ঝালকাঠি',
    'Patuakhali': 'পটুয়াখালী',
    'Pirojpur': 'পিরোজপুর',
    'Sylhet City': 'সিলেট সিটি',
    'Habiganj': 'হবিগঞ্জ',
    'Moulvibazar': 'মৌলভীবাজার',
    'Sunamganj': 'সুনামগঞ্জ',
    'Sylhet': 'সিলেট',
    'Rangpur City': 'রংপুর সিটি',
    'Dinajpur': 'দিনাজপুর',
    'Gaibandha': 'গাইবান্ধা',
    'Kurigram': 'কুড়িগ্রাম',
    'Lalmonirhat': 'লালমনিরহাট',
    'Nilphamari': 'নীলফামারী',
    'Panchagarh': 'পঞ্চগড়',
    'Rangpur': 'রংপুর',
    'Thakurgaon': 'ঠাকুরগাঁও',
    'Mymensingh City': 'ময়মনসিংহ সিটি',
    'Jamalpur': 'জামালপুর',
    'Mymensingh': 'ময়মনসিংহ',
    'Netrokona': 'নেত্রকোণা',
    'Sherpur': 'শেরপুর',

    // Categories
    'Electronics': 'ইলেকট্রনিক্স',
    'Vehicles': 'যানবাহন',
    'Property': 'প্রপার্টি',
    'Jobs': 'চাকরি',
    'Mobile Phones': 'মোবাইল ফোন',
    'Computers': 'কম্পিউটার',
    'অন্যান্য': 'অন্যান্য',
    'TVs & Audio': 'টিভি ও অডিও',
    'Cars': 'গাড়ি',
    'Motorcycles': 'মোটরসাইকেল',
    'For Rent': 'ভাড়ার জন্য',
    'For Sale': 'বিক্রির জন্য',

    // Subcategories & Specific Items
    'Smartphones': 'স্মার্টফোন',
    'Feature Phones': 'ফিচার ফোন',
    'Accessories': 'অ্যাক্সেসরিজ',
    'Used Phones': 'ব্যবহৃত ফোন',
    'Laptops': 'ল্যাপটপ',
    'Desktops': 'ডেস্কটপ',
    'Components': 'কম্পিউটার পার্টস',
    'Cameras': 'ক্যামেরা',
    'Kitchen Appliances': 'রান্নাঘরের সরঞ্জাম',
    'Other Electronics': 'অন্যান্য ইলেকট্রনিক্স',
    'Electric Vehicles': 'বৈদ্যুতিক যানবাহন',
    'Bicycles': 'সাইকেল',
    'Commercial Vehicles': 'বাণিজ্যিক যানবাহন',
    'Water Transport': 'জলযান',
    'Spare Parts & Accessories': 'খুচরা যন্ত্রাংশ ও অ্যাক্সেসরিজ',
    'PG & Hostel': 'পিজি ও হোস্টেল',
    'IT & Telecom': 'আইটি ও টেলিকম',
    'Sales & Marketing': 'সেলস ও মার্কেটিং',
    'Customer Service': 'কাস্টমার সার্ভিস',
    'Garments & Textile': 'গার্মেন্টস ও টেক্সটাইল',
    'Driver & Transport': 'ড্রাইভার ও পরিবহন',
    'Home & Living': 'হোম ও লিভিং',
    'Fashion': 'ফ্যাশন',
    'Sports & Hobbies': 'খেলাধুলা ও শখ',
    'Animals & Pets': 'প্রাণী ও পোষা প্রাণী',
    'Agriculture': 'কৃষি',
    'Services': 'সেবাসমূহ',

    'Televisions': 'টেলিভিশন',
    'Home Theater': 'হোম থিয়েটার',
    'Speakers': 'স্পিকার',
    'Sound System': 'সাউন্ড সিস্টেম',
    'DSLR': 'ডিএসএলআর',
    'Digital Cameras': 'ডিজিটাল ক্যামেরা',
    'Action Cameras': 'অ্যাকশন ক্যামেরা',
    'Camera Accessories': 'ক্যামেরার অ্যাক্সেসরিজ',
    'Refrigerator': 'রেফ্রিজারেটর',
    'Washing Machine': 'ওয়াশিং মেশিন',
    'Microwave': 'মাইক্রোওয়েভ',
    'Blender': 'ব্লেন্ডার',
    'AC': 'এসি',
    'Fan': 'ফ্যান',
    'Iron': 'ইস্ত্রি',
    'Generator': 'জেনারেটর',
    'UPS': 'ইউপিএস',
    'Android Phones': 'অ্যান্ড্রয়েড ফোন',
    'iPhones': 'আইফোন',
    'Budget Phones': 'বাজেট ফোন',
    'Gaming Phones': 'গেমিং ফোন',
    'Basic Phones': 'বেসিক ফোন',
    'Button Phones': 'বাটন ফোন',
    'Cases & Covers': 'কেস ও কভার',
    'Screen Protectors': 'স্ক্রিন প্রটেক্টর',
    'Chargers': 'চার্জার',
    'Earphones': 'ইয়ারফোন',
    'Power Banks': 'পাওয়ার ব্যাংক',
    'Used Android': 'ব্যবহৃত অ্যান্ড্রয়েড',
    'Used iPhone': 'ব্যবহৃত আইফোন',
    'Used Feature Phones': 'ব্যবহৃত ফিচার ফোন',
    'Gaming Laptops': 'গেমিং ল্যাপটপ',
    'Business Laptops': 'বিজনেস ল্যাপটপ',
    'Student Laptops': 'স্টুডেন্ট ল্যাপটপ',
    'MacBooks': 'ম্যাকবুক',
    'Gaming Desktops': 'গেমিং ডেস্কটপ',
    'Office PCs': 'অফিস পিসি',
    'All-in-One PCs': 'অল-ইন-ওয়ান পিসি',
    'Processors': 'প্রসেসর',
    'RAM': 'র‍্যাম',
    'Graphics Cards': 'গ্রাফিক্স কার্ড',
    'Motherboards': 'মাদারবোর্ড',
    'Storage': 'স্টোরেজ',
    'Monitors': 'মনিটর',
    'Keyboards': 'কীবোর্ড',
    'Mouse': 'মাউস',
    'Webcams': 'ওয়েবক্যাম',
    'Printers': 'প্রিন্টার',
    'Routers': 'রাউটার',
    'Toyota': 'টয়োটা',
    'Honda': 'হোন্ডা',
    'Nissan': 'নিসান',
    'Mitsubishi': 'মিৎসুবিশি',
    'Mazda': 'মাজদা',
    'Hyundai': 'হুন্দাই',
    'Kia': 'কিয়া',
    'BMW': 'বিএমডব্লিউ',
    'Mercedes': 'মার্সিডিজ',
    'Audi': 'অডি',
    'Volkswagen': 'ভক্সওয়াগেন',
    'Maruti': 'মারুতি',
    'Tata': 'টাটা',
    'Bajaj': 'বাজাজ',
    'Hero': 'হিরো',
    'TVS': 'টিভিএস',
    'Royal Enfield': 'রয়্যাল এনফিল্ড',
    'Yamaha': 'ইয়ামাহা',
    'Suzuki': 'সুজুকি',
    'Kawasaki': 'কাওয়াসাকি',
    'Lifan': 'লিফান',
    'Zongshen': 'জংশেং',
    'Electric Cars': 'বৈদ্যুতিক গাড়ি',
    'Electric Motorcycles': 'বৈদ্যুতিক মোটরসাইকেল',
    'Electric Scooters': 'বৈদ্যুতিক স্কুটার',
    'Mountain Bikes': 'মাউন্টেন বাইক',
    'BMX': 'বিএমএক্স',
    'Road Bikes': 'রোড বাইক',
    'Kids Bicycles': 'বাচ্চাদের সাইকেল',
    'Trucks': 'ট্রাক',
    'Vans': 'ভ্যান',
    'Buses': 'বাস',
    'CNG': 'সিএনজি',
    'Auto Rickshaw': 'অটো রিকশা',
    'Boats': 'নৌকা',
    'Speedboats': 'স্পিডবোট',
    'Car Parts': 'গাড়ির পার্টস',
    'Bike Parts': 'বাইকের পার্টস',
    'Tyres': 'টায়ার',
    'Batteries': 'ব্যাটারি',
    'Helmets': 'হেলমেট',
    'Jackets': 'জ্যাকেট',
    'Apartments': 'অ্যাপার্টমেন্ট',
    'Houses': 'বাড়ি',
    'Commercial Property': 'বাণিজ্যিক সম্পত্তি',
    'Rooms': 'রুম',
    'Office Space': 'অফিস স্পেস',
    'Land': 'জমি',
    'Plots': 'প্লট',
    'Male Hostel': 'ছাত্রাবাস (ছেলে)',
    'Female Hostel': 'ছাত্রীনিবাস (মেয়ে)',
    'PG Accommodation': 'পেয়িং গেস্ট',
    'Software Engineer': 'সফটওয়্যার ইঞ্জিনিয়ার',
    'Web Developer': 'ওয়েব ডেভেলপার',
    'Network Admin': 'নেটওয়ার্ক অ্যাডমিন',
    'UI/UX Designer': 'ইউআই/ইউএক্স ডিজাইনার',
    'Data Analyst': 'ডাটা অ্যানালিস্ট',
    'Sales Executive': 'সেলস এক্সিকিউটিভ',
    'Marketing Manager': 'মার্কেটিং ম্যানেজার',
    'Digital Marketer': 'ডিজিটাল মার্কেটার',
    'Call Center': 'কল সেন্টার',
    'Support Executive': 'সাপোর্ট এক্সিকিউটিভ',
    'Help Desk': 'হেল্প ডেস্ক',
    'Garments Worker': 'গার্মেন্টস কর্মী',
    'Quality Inspector': 'কোয়ালিটি ইন্সপেক্টর',
    'Merchandiser': 'মার্চেন্ডাইজার',
    'Car Driver': 'গাড়ি চালক',
    'Truck Driver': 'ট্রাক চালক',
    'Bike Rider': 'বাইক রাইডার',
    'Furniture': 'আসবাবপত্র',
    'Home Appliances': 'গৃহস্থালী সামগ্রী',
    'Kitchen Items': 'রান্নাঘরের জিনিসপত্র',
    'Bedding': 'বিছানা ও চাদর',
    'Decor': 'সাজসজ্জা',
    "Men's Clothing": 'পুরুষের পোশাক',
    "Women's Clothing": 'নারীর পোশাক',
    'Shoes': 'জুতো',
    'Bags': 'ব্যাগ',
    'Jewelry': 'গহনা',
    'Sports Equipment': 'খেলার সামগ্রী',
    'Musical Instruments': 'বাদ্যযন্ত্র',
    'Books': 'বই',
    'Games & Toys': 'খেলা ও খেলনা',
    'Dogs': 'কুকুর',
    'Cats': 'বিড়াল',
    'Birds': 'পাখি',
    'Fish': 'মাছ',
    'Pet Accessories': 'পোষা প্রাণীর সামগ্রী',
    'Seeds & Plants': 'বীজ ও চারা',
    'Fertilizers': 'সার',
    'Farm Equipment': 'খামার সরঞ্জাম',
    'Livestock': 'গবাদি পশু',
    'Repair Services': 'মেরামত সেবা',
    'Cleaning Services': 'পরিচ্ছন্নতা সেবা',
    'Tutoring': 'গৃহশিক্ষক',
    'Event Management': 'ইভেন্ট ম্যানেজমেন্ট',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('lang');
    if (savedLang) setLang(savedLang);
  }, []);

  const toggleLanguage = () => {
    const newLang = lang === 'en' ? 'bn' : 'en';
    setLang(newLang);
    localStorage.setItem('lang', newLang);
  };

  const t = (key) => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
